# Only test building images
name: PullRequest

on:
  pull_request:
    branches:
      - main

env:
  DOCKER_ORG: coffeateam
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:

  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE_DIR: [base, base-cc7]
    name: ${{ matrix.IMAGE_DIR }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Image
      run: |
        IMAGE=coffea-${{ matrix.IMAGE_DIR }}
        echo "IMAGE=${IMAGE}" >> $GITHUB_ENV

        pushd ${{ matrix.IMAGE_DIR }}

        # take care of default image first
        docker build -f Dockerfile -t ${DOCKER_ORG}/${IMAGE}:PR .
        # run any specialized builds
        for spec in $(ls | grep -v Dockerfile)
	do
	  docker build -f Dockerfile -t ${DOCKER_ORG}/${IMAGE}:${spec}-PR --build-arg COFFEA_BASE_IMAGE=${DOCKER_ORG}/${IMAGE}:PR .
	done

	popd	
    - name: Export Full Conda Environment
      run: |
        pushd ${{ matrix.IMAGE_DIR }}
        # take care of the default image first
        docker run ${DOCKER_ORG}/${IMAGE}:PR conda list --export
        for spec in $(ls | grep -v Dockerfile)
        do
	  echo specialization: ${spec}
          docker run ${DOCKER_ORG}/${IMAGE}:${spec}-PR conda list --export
        done

        popd